---
- name: Download a file
  ansible.builtin.get_url:
    url: http://ipv4.download.thinkbroadband.com/5MB.zip
    dest: /tmp
    mode: "0644"
    owner: vagrant
    group: vagrant
  become: false

- name: Add an environment variable to the remove user's shell
  ansible.builtin.lineinfile:
    dest: "~/.profile"
    regexp: "^ENV_VAR="
    line: "ENV_VAR=value"
  # disable sudo so it doesn't reference the root user's bash profile
  become: false

- name: Get the value of an environment variable
  # the command module doesn't work with the double ampersand,
  # so we use the shell module
  ansible.builtin.shell: "source  ~/.profile && echo $ENV_VAR"
  changed_when: false
  args:
    executable: "/bin/bash"
  # ansible wouldn't know to print the 'echo $ENV_VAR' above,
  # so we register the variable, and it would also give a dictionary
  # containing the stdout and stderr by line
  register: foo

- name: Debug environment variable
  ansible.builtin.debug:
    msg: "The variable is {{ foo.stdout }}"

- name: Install Apache
  ansible.builtin.apt:
    name:
      - apache2
      - apache2-utils
    state: present
    update_cache: false

- name: Copy configuration files.
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - src: vhosts.conf
      dest: /etc/apache2/sites-available/default.conf
  notify: Restart apache
- name: Make sure handlers are flushed immediately.
  ansible.builtin.meta: flush_handlers

- name: Enable virtual host.
  ansible.builtin.file:
    src: /etc/apache2/sites-available/default.conf
    dest: /etc/apache2/sites-enabled/default.conf
    state: link
  notify: Restart apache

- name: Ensure Apache is started and enabled at boot.
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
