---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  env:
    ANSIBLE_REMOTE_TMP: /tmp/.ansible
