---
- name: Install Apache
  hosts: all
  become: true
  gather_facts: true

  # A handler is just a task that's ran at the
  # end of the playbook using the `notify` module.
  handlers:
    - ansible.builtin.import_tasks: handlers/apache.yml
  tasks:
    - import_tasks: tasks/apache.yml

