
Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.ssh.insert_key = false

    config.vm.synced_folder ".", disabled: true

    config.vm.provider :virtualbox do |v|
        v.memory = 512
        v.linked_clone = true
    end

    config.vm.define "app1" do |app|
        app.vm.hostname = "orc-app1.test"
        app.vm.network :private_network, ip: "192.168.60.4"
    end
end