---
- name: Demonstrate ansible-lint
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Get system uptime to demo how this works
      ansible.builtin.command: uptime
      changed_when: false
      register: system_uptime

    - name: Print the registered output of the 'uptime' command
      ansible.builtin.debug:
        var: system_uptime.stdout
