---
- name: Demonstrate debug module and register variable
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Register the output of the 'uptime' command
      ansible.builtin.command: uptime
      register: system_uptime
      changed_when: false
      notify: Print debug message

    - name: Print the registered output of the 'uptime' command
      ansible.builtin.debug:
        var: system_uptime.stdout

  handlers:
    - name: Print debug message
      ansible.builtin.debug:
        msg: "Command resulted in a change"
