---
- name: Demonstrate Syntax Check
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    # Syntax check will pass whether or not this file exists
    - name: Include dates tasks
      ansible.builtin.include_tasks: dates.yml

    # This will cause a failure because the file doesn't exists,
    # since it can be checked statically
    - name: Include free tasks
      import_tasks: free.yml

    - name: Print a debug message
      ansible.builtin.debug:
        msg: "Hello there!"
